server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://kaamelott.chaudie.re/api/;
        proxy_set_header Host kaamelott.chaudie.re;
        proxy_ssl_server_name on;
    }
}